### ISSUE TITLE
Readings

### ISSUE THREAD

**Issue by Mikerah** [eth-spy/eth-spy#1]
- [Devp2p spec](https://github.com/ethereum/devp2p)
- [CoinScope](http://www.cs.umd.edu/projects/coinscope/coinscope.pdf)
    - Associated codebase: https://github.com/jameslitton/coinscope
- [Measuring Ethereum Network Peers](http://joshm.web.engr.illinois.edu/imc18_ethereum.pdf)
    - Associated codebase: https://github.com/teamnsrg/ethereum-p2p/tree/node-finder-master
- [Low-Resource Eclipse Attacks on Ethereum's Peer-to-Peer Network](https://eprint.iacr.org/2018/236.pdf)
- [Using Ethereum Transactions To Deanonymize Senders](https://www.ideals.illinois.edu/bitstream/handle/2142/101616/MURALI-THESIS-2018.pdf?sequence=1&isAllowed=y)
    - Chapter 2
    - Chapter 3
    - Associated codebase: https://github.com/teamnsrg/ethereum-p2p/tree/tx-sniper-master

**Comment by gengmoqi** [comment]
Paddy: Create slides "How does ETH do handshakes"
